### ISSUE TITLE
Additional info for mixpanel / log files to help debugging

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#103]
In light of our inability to reproduce #101, I'm wondering if there is any information we can log or send to mixpanel that might help us out. We have OS, JRE, app version, & timezone. Maybe also...
- graphics card information
- screen resolution & game window size/resolution

There's got to be more, I'm just not sure what would be most useful and how to get to it through libgdx.

**Comment by BrianErikson** [comment]
Ported over to trello
