### ISSUE TITLE
Box2D Crash in Arcade mode

### ISSUE THREAD

**Issue by BrianErikson** [EmergentOrganization/cell-rpg#104]
When I was wandering around the area in Arcade, a few times I have crashed to desktop with the following stack trace:

```
[INFO]  13:35:17.795    game.Arcade.<init>  -   enter arcade mode
[INFO]  13:35:26.319    regions.WarpInEventRegion.getNextRegion -   leaving TimedRegion. Time spent in region:7004
[INFO]  13:35:33.343    regions.WarpInEventRegion.getNextRegion -   leaving TimedRegion. Time spent in region:7008
java: /var/lib/jenkins/workspace/libgdx/extensions/gdx-box2d/gdx-box2d/jni/Box2D/Dynamics/b2Body.cpp:168: b2Fixture* b2Body::CreateFixture(const b2FixtureDef*): Assertion `m_world->IsLocked() == false' failed.
```

I haven't pinned down where it goes wrong, but it seems to occur when changing regions?

**Comment by 7yl4r** [comment]
I haven't seen this one before. I'm not sure what causes the world to be
locked, and the region change should only be scheduling new entities to
warp in, but their creation is delayed until after the warp effect is over.

**Comment by BrianErikson** [comment]
Might be a duplicate with #111. Will close for now, and re-open if I run into it again.
