### ISSUE TITLE
Enemies not damaging?

### ISSUE THREAD

**Issue by BrianErikson** [EmergentOrganization/cell-rpg#105]
These circular enemies just bump you around instead of damaging the player:
![image](https://cloud.githubusercontent.com/assets/7645647/15801107/5d5a23c8-2a8b-11e6-9f65-2d959413eca2.png)

**Comment by 7yl4r** [comment]
Yes, this was _sort of_ intentional... I was just trying to play with
different gameplay mechanics. These guys are more of a nuisance than a
danger right now.

**Comment by 7yl4r** [comment]
Maybe this would be a more interesting gameplay mechanic if they bumped a
bit harder. I'm not quite sure how the values in box2d work though. Maybe
we want to increase the elasticity or mass of these enemies?
