### ISSUE TITLE
Art-style experimentation : pixel-art

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#106]
The art right now doesn't blend well. Vyroids and my vector graphics seem disconnected when they should be nearly seamless. 

Let's try something different!

How about some pixel-art concepts? I'm especially interested in how we can get graphics to work together with CA.

**Comment by 7yl4r** [comment]
Might also be worth checking #37 for inspiration.

**Comment by 7yl4r** [comment]
Most recent three animations on my piskel profile for this came out meh http://www.piskelapp.com/user/4633761060749312

**Comment by BrianErikson** [comment]
I went for a sort of cybernetic feel for another version of a Vyrapuffer... It came out okay.
![vryagrunt](https://cloud.githubusercontent.com/assets/7645647/15925842/286c61a6-2e39-11e6-8080-860320ab944b.gif)

**Comment by 7yl4r** [comment]
I think we're definitely moving in the right direction. I like the energy moving through the tracks and the shading around the edges.

 I have been having a lot of trouble picking a color palette for the vyroids since the actual cells can be so multicolored. On one hand in wondering if the vyroids should be limited in their colors to better blend with their textures, but on the other hand I really like the chaotic multi-colored static look.

**Comment by BrianErikson** [comment]
I created an [Adobe Color CC color scheme](https://color.adobe.com/create/color-wheel/?base=2&rule=Compound&selected=2&name=My%20Color%20Theme&mode=rgb&rgbvalues=0.07999999999999999,0.4467388576485428,0.8,0.24,0.42336942882427137,0.6,0,1,0.9616322094875613,1,0.4028807809584123,0.25,0.8,0.12176554971963922,0.07999999999999999&swatchOrder=0,1,2,3,4) that might work. Feel free to play around -- it might spark some ideas for you

**Comment by BrianErikson** [comment]
Ported over to trello
