### ISSUE TITLE
Character Development : The Professor

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#107]
Our game's (barely extant) story has the player acting through a technological creation made by a [mad scientist](http://tvtropes.org/pmwiki/pmwiki.php/Main/MadScientist)/[professor](http://tvtropes.org/pmwiki/pmwiki.php/Main/TheProfessor) type character. 

This character needs to be developed. (S)he needs a good name and a wikia page.

Here's what I have so far:
The professor is a very desperate, eccentric, and slightly malfunctioning/insane member of the ["seeker"](http://planiverse-bridge.wikia.com/wiki/Seeker) species who has created a bridge between universes in search of someone who can return balance to Pixelon. This bridge was created in spite of the Seeker Council's Dictum and the general negative public view of inter-dimensional communications. 

The professor's extremist beliefs hold that the Vyroids are at odds with balance, and that they are a consuming force which should be resisted at any cost. These views put him at odds with the Seeker Council, who take pacifism to the extreme and have already accepted their consumption by the Vyroids as an inevitable and harmonious next phase which will bring greater balance to Pixelon.

The professor is not completely alone in his beliefs, however. As Vyroids consume more of Pixelon those who resist their spread have come together at the Stronghold to make a last stand. Without any means and a strong natural aversion to violence in any form, however, it seems that there is little hope.

**Comment by BrianErikson** [comment]
Ported over to trello
