### ISSUE TITLE
main menu beautification 

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#109]
The main menu is a bit plain. We need a fun background scene.

A simple CA background should suffice for now. We probably want to use a "Methuselah" pattern or  else we may want to spawn shapes (eg gliders) into the background. The only CA rule implemented currently is CGoL, but if there is something else we want for the menu, I would be happy to work on the CA engine so we can support it. 

As for the layer type, the GeneticLayer is my pride and joy, so I suggest we use that. However, the computational demands for this one are a bit high, so I won't be too hurt if we want to use a different layer type.

What does everyone think? 
- Methuselah or gliders? 
- CGoL or something else? 
- Genetic cells or no?

**Comment by BrianErikson** [comment]
It would be very cool to make our logo or icon for the game using a Methuselah pattern, and then having the CA form the pattern in the main menu :sunglasses:

**Comment by BrianErikson** [comment]
A Centinal period 100 Oscillator might look pretty cool if it animates behind "Pixelon Transmission" or something
![centinal](https://cloud.githubusercontent.com/assets/7645647/15848026/8b731962-2c8a-11e6-99ef-d2618ef2f424.gif)

**Comment by BrianErikson** [comment]
Ported issue over to trello board
