### ISSUE TITLE
use new player sprite

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#11]
replace the previously used light.png with the new animated player sprite in `android/assets/char-player/`

![Imgur](http://i.imgur.com/BjXRs1t.gif)

**Comment by 7yl4r** [comment]
started @ https://github.com/EmergentOrganization/cell-rpg/tree/newPlayerSprite, but it's taking a while for my java to get warmed up.

**Comment by orelb** [comment]
Hey @7yl4r, you need to use the `play()` method in GraphicsComponent. 

For example, if you registered an animation titled "anim1" simply use `graphicsComponent.play("anim1")`
Any animation settings, such as looping is already available through Gdx's Animation class.

**Comment by 7yl4r** [comment]
Hmm, still not having any luck...

``` java
        this.graphicsComponent = new GraphicsComponent();
        graphicsComponent.register("body", bodyAnimation);
        addComponent(graphicsComponent);
        graphicsComponent.play("body");
```

([context](https://github.com/EmergentOrganization/cell-rpg/blob/newNewPlayerSprite/core/src/com/emergentorganization/cellrpg/entities/characters/Character.java#L28-L31))
Probably something silly. I haven't given up yet though.
