### ISSUE TITLE
CamShake

### ISSUE THREAD

**Issue by BrianErikson** [EmergentOrganization/cell-rpg#110]
As I was going through TODOs, I noticed that the camshake doesn't actually work? TODO!

**Comment by 7yl4r** [comment]
Yes! This is weird, but if you turn it on fps goes wayyyy down. Might be an
easy fix I just haven't looked at it yet.

**Comment by BrianErikson** [comment]
To explain, the `camShake` was being overridden by the `camFollow` method. To fix this, I altered the shake method to push a task to an array which is ran during the processing of the `CameraSystem` class. I also added a `Vector2 gameCamDelta` to aid in the clarity of this, which actually moves the camera in the `end` method of the system.
