### ISSUE TITLE
Unified Spawning System

### ISSUE THREAD

**Issue by BrianErikson** [EmergentOrganization/cell-rpg#111]
Since we probably want to use the warping effect for every entity that is not CA when it is instantiated into the game, I propose that the ApparitionCreator turn into an Artemis system, and be the focal point of all runtime spawning needs. 

Right now, I think the spawning is shared between multiple classes, resulting in weird chains of dependencies.

**Comment by BrianErikson** [comment]
This would also solve the issue where Box2D resources are never disposed of because of TimerTasks running way after the scene has been disposed

**Comment by BrianErikson** [comment]
@7yl4r, when you get a moment, I'd like your help in tweaking all of the values that got borked from the refactor on branch `111_refactor`. Everything is working (quite well!), but all the values need tweaking to get where they were before. 

Only when you have the chance, though. If not, I'll continue playing around with them until it feels right. Right now it's crazy hectic, but I actually like it a lot this way. I just don't want to merge it into master with crazy spawn rates and stuff

**Comment by 7yl4r** [comment]
Wow, you've been busy! I just finished reading through the diffs and I pushed a little change to fix the powerup spawn frequency. Is there any other values you noticed are different? The rest looks about the same I think.
