### ISSUE TITLE
use texture atlas

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#14]
and [texture packer](https://github.com/libgdx/libgdx/wiki/Texture-packer), and maybe [the gui as well](http://www.aurelienribon.com/blog/2012/06/texturepacker-gui-v3-0-0/)

**Comment by 7yl4r** [comment]
I gave the GUI a shot and didn't get it working. The instructions I'm using seem a bit out-of-date. I forget, have you used this before @BrianErikson ?

**Comment by BrianErikson** [comment]
I have; I'll take a stab at it in like 12 hours

**Comment by 7yl4r** [comment]
We're going to need to make some changest GraphicsComponent so it will work with a textureAtlas, but that shouldn't be too much trouble. I couldn't seem to get the program to load in any images though, and so I always ended up with an empty atlas.

**Comment by BrianErikson** [comment]
Yeah I think it's a bug in the program with linux directories... It worked fine on windows. I'll have to figure out how to do it manually

**Comment by 7yl4r** [comment]
I'll have to give it another shot on my laptop.

**Comment by BrianErikson** [comment]
#64 closes this issue. Run the TexPacker class in the desktop project to recompile assets if they have changed

**Comment by 7yl4r** [comment]
I've figured out where to put the sprites and I got TexPacker working, is there anything special we need to do to get these to work in the code?

**Comment by BrianErikson** [comment]
Not really; it looks like you've handled it in your recent commits. The only key thing would be to create the sprite from the texture region in the atlas, but [our components handle that for us](https://github.com/EmergentOrganization/cell-rpg/blob/master/core/src/com/emergentorganization/cellrpg/components/entity/SpriteComponent.java#L27)
