### ISSUE TITLE
glow shader

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#15]

**Comment by BrianErikson** [comment]
Sources for personal reference:
http://http.developer.nvidia.com/GPUGems/gpugems_ch21.html
https://www.shadertoy.com/view/XdX3WN#
https://www.shadertoy.com/view/XdXXzr
https://www.shadertoy.com/view/XtB3Wc

**Comment by BrianErikson** [comment]
Unassigning myself while I work on other things

**Comment by 7yl4r** [comment]
note (in case anyone else wants to play with this): ongoing progress on the TronShader and shaderDev branches.

**Comment by 7yl4r** [comment]
I just occurred to me that it may be helpful to share how I achieved this glow in inkscape:

![Imgur](http://i.imgur.com/v3IsxUv.png)

It is made up of two blurs, one with a small radius and low transparency and another with a large radius and high transparency. I think we could take the same two-shader approach in post-processing, but I think this is roughly equivalent to using a negative exponential falloff ramp which would be more efficient (I think).

**Comment by BrianErikson** [comment]
This is mostly done with this commit https://github.com/EmergentOrganization/cell-rpg/commit/4355136b4b732d6861e65157ec8ab8f4b86016ee

We still need to refine the effect we want and port the assets to use it as well.

To use the TronShader in the scene, please reference the BlurTest scene for an example. To blur a pixel,~~set it with a 127/255 alpha value~~(no longer true. It is based on a color parameter now)

**Comment by BrianErikson** [comment]
![blurpass](https://cloud.githubusercontent.com/assets/7645647/9698880/61b19dbc-53cb-11e5-952d-9fbc19d1e187.png)
I think it's sufficient enough for now so I'm going to close this issue
