### ISSUE TITLE
map texture improvements

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#16]
Right now the map texture background is a simple effect from gimp under render->circuit traces. I'd like to be a lot more creative with this, and possibly generate the base texture using a script. 

There are tons of options out there, so it really just comes down to what we want to try out first. Some options:
1. read in base texture at game-run and procedurally modify. Could also include CAs. Input might then be reduced to a "biome" area marked on the game texture.
2. pre-rendered map, various rendering steps (such as current use of circuit traces) to produce an interesting map which can be manually tweaked and then saved as a png.

**Comment by 7yl4r** [comment]
[Here's one link with some maze-style-textures](http://www.janthor.com/maze/) I think might work well with the art style (python scripts to generate them at bottom of page.)

**Comment by BrianErikson** [comment]
A critical thing to note is that we'll probably need the texture to be tile-able without visible seams as well.

**Comment by BrianErikson** [comment]
ported to trello
