### ISSUE TITLE
determine minimum performance target

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#17]
Lower res and lower fps will help greatly allow normally heavy CA algos to run on shitty hardware. Some trial and error will be essential when it comes to guesstimating how many devices we want to exclude from playing this game. That's what this will come down to - some will have enough to run it, and some won't. Where do we set that line?

Figuring this out is crucial to planning out the CA engine.

I know we have previously decided to target android 4+ only, and our project is currently targeting 5.0, but what other "minimum system requirements" should we lay down?

Additionally, how can we limit the CA rules to keep them from hogging CPU/GPU time? These algorithms can be very resource-intensive and if run with no regard for the hardware, or software running alongside them, they will destroy CPU and GPU hardware by running it at max.

**Comment by 7yl4r** [comment]
My extremely brief opinion on this is "let's target the newest mobile devices and wait until people buy them".

**Comment by BrianErikson** [comment]
Judging by [this chart](http://www.appbrain.com/stats/top-android-sdk-versions), supporting android versions 4+ will cover 90% of all devices. Seeing as most relatively 'new' devices (from the last four years) can render 3D just fine, I don't think we will have to worry about optimization _too_ much at the start. As they say, _Premature optimization is the root of all evil_.
