### ISSUE TITLE
Improving movement system

### ISSUE THREAD

**Issue by orelb** [EmergentOrganization/cell-rpg#19]
The movement system needs an improvement.

> InfiniteSearchSpace: I have some thoughts on options for the movement system:
> If the user is drawing waypoints close (say, within 100px) to the player, don't engage waypoint movement at all - instead use direct player-to-mouse line for direct control over movement.
> The user should be able to use this mode (or long-tap close to the player) to erase/cancel any current or long drawn waypoint paths.
> If waypoints are drawn through solid obstacles, 'end' the waypoint, or set the waypoint along the edge of the structure. Maybe use some simple pathing algos to route around smaller or simple shaped obstacles. Maybe also modify the collision handling to make walls 'slippery'.
> Place an upper limit on the number of waypoint coordinates, and/or the maximum/minimum distance between coordinates.
> 'Join together' or apply smoothing to waypoint coordinates that are very close/clustered or erratically placed, with either smooth curves or with sharp corners & straight lines. I feel that using raw position data for the movement makes for a choppy experience.
> Another annoyance is that the camera position affects where the waypoints are placed. A full decoupling of these aspects may not be best, but the effect is far to pronounced at the moment IMO.

If anybody got thoughts on the movement system please write them down.

**Comment by orelb** [comment]
1efd09f668a063cefc4f8bb09c748ed3bfeab9f0 Movement now has two options:
1. Direct player to mouse movement if the distance of the player to the mouse is small.
2. Moving along a path if the distance from the player to the mouse is big (only the initialization of the path, once you began drawing a path you can draw it very close to the player)

Note: a path movement will stop if the player will use (1). You need to click the mouse (not press).

**Comment by InfiniteSearchSpace** [comment]
The movement system is much improved! 

I find Direct-control mode is too quick to activate, and can interfere with attempts to shoot while stationary or while following a waypoint path. I'd recommend waiting for a long-tap with the same delay as the older version (200ms?) before activating or committing the player to any movement-related action.

I think the direct-control radius is too big. I reccommend an area reduction of 66% - 80%.

**Comment by InfiniteSearchSpace** [comment]
The movement system is much improved! 

I find Direct-Control mode is too quick to activate, and can interfere with attempts to shoot while stationary or while following a waypoint path. I'd recommend waiting for a long-tap with the same delay as the older version (200ms?) before activating or committing the player to any movement-related action.

I think the Direct-Control radius is too big. I recommend an area reduction to 66% - 80% of the current radius.

**Comment by 7yl4r** [comment]
perhaps we ought to treat some of these values as preferences?

**Comment by InfiniteSearchSpace** [comment]
Agreed, customization on core features - like movement controls - is important. More-so on a cross-platform application.

**Comment by 7yl4r** [comment]
After #31 is in place, let's get some movement customization into the settings and then we can close this one off.

**Comment by orelb** [comment]
@7yl4r, I'll get the settings thing done today. I think we should give the player the chance to choose the type of movement he wants to use: direct player to mouse in short distance and path drawing or only direct to mouse movement. Either one should be customizable.

**Comment by 7yl4r** [comment]
That sounds great. I agree about putting in multiple control schemes if it isn't too much work.

**Comment by 7yl4r** [comment]
so now that we have movement options in the settings screen, we can add alternative control schemes. I think I will do WASD movement + click-to-shoot next. Any other requests?

**Comment by 7yl4r** [comment]
Though I have some more ideas for movement controls and options we could try out, I'm going to close this since I think the issues discussed are resolved and future improvements likely warrant their own issue.
