### ISSUE TITLE
CameraFollowComponent

### ISSUE THREAD

**Issue by orelb** [EmergentOrganization/cell-rpg#21]
We need to take out the rubber-banding code from the update method of the entity class. We want to abstract it to its own component.

**Comment by orelb** [comment]
> InfiniteSearchSpace: Another issue with movement/camera interaction: I feel the camera adjusts in the wrong direction relative to movement - When moving up, for example, the camera view shows a large 'backlog' of the game world below the player, giving the player very little time to react to anything they're about to encounter. The user should be able to loosely remember what objects are off screen from areas they've recently visited, so it makes little sense to show them that information. If a player is moving upwards, the camera angle should sit the player at the bottom boundary of the view screen, giving them a fair forewarning of the territory they are moving towards.

**Comment by 7yl4r** [comment]
I'll happily do it, but i do want to ask why. I can't imagine any other entity this component would be useful for, and if it's just too clean up the update method, maybe we can just move things to their own method "updateCameraPos"? 

Regarding the 2nd suggestions: I agree with them and will implement after deciding if this needs to be component-ified.

**Comment by BrianErikson** [comment]
Components are supposed to be re-usable functionality which are independent of any classes. If you only plan on using the functionality in a single class then it wouldn't make any sense to make a component for it IMO

**Comment by 7yl4r** [comment]
I've moved the camera positioning to a separate method to clean up `update`, and have attempted to improve movement a bit. However, anticipating player movement is much harder than leading behind, and the current implementation makes camera movement too volatile IMO.

Try tweaking these three constants to get different camera feels in Entities.Player:

``` java
 // camera behavior:
private static final int EDGE_MARGIN = 100;  // min px between player & screen edge
private static final int CLOSE_ENOUGH = 40;  // min distance between player & cam we care about (to reduce small-dist jitter & performance++)
private static final float CAMERA_LEAD = 200;  // dist camera should try to lead player movement
```

It's possible I could smooth this leading behavior out even further, but we might do better just to keep the player closer to the middle by increasing `EDGE_MARGIN`.

**Comment by BrianErikson** [comment]
Zooming in the camera has messed with this a tad. I tried to rectify it by scaling the numbers above appropriately, but it still feels pretty stiff

**Comment by orelb** [comment]
@BrianErikson I thought we might find it useful in case of switching the player entity. But I think that leaving the code in another method is just fine for now.

**Comment by 7yl4r** [comment]
Oh, that's a good point.

**Comment by BrianErikson** [comment]
I can agree with that, @orelbitton

**Comment by 7yl4r** [comment]
Looking at this again, I think maybe it makes even more sense to define the camera as an entity which attaches to another target entity. Here's a breakdown of how I'm imagining the two approaches to switching camera targets:

1) camera-movement component + camera: copy camera object to new target, del old ref, create new cameraMove component on new target, del old component.

2) camera-entity: set new target entity, camera object retained, cameraMove component retained.

However, I'm concerned that storing a reference to another entity breaks our design paradigm, what do you guys think?

**Comment by BrianErikson** [comment]
No, that should be fine! The CameraEntity can just have a `setTarget(Entity)` and a `removeTarget()` and just update the camera's position in the update method to match the target. It would only break the paradigm if the CameraEntity needed a target reference outside of the runtime (i.e a static reference)

**Comment by 7yl4r** [comment]
for detail on the issue mentioned in efbd8b7, see the snippit below from scenes/Test.java:

``` java
        Map map = MapTools.importMap("TestMap");
        addEntities(map.getEntities());

        // TODO: these two should match now?!? (but they don't, Test.getEntities() is empty!)
        System.out.println(getEntities());
        System.out.println(map.getEntities());

        addEntity(new FollowingCamera(getPlayer()));  // TODO: this fails b/c there is no player in empty array
```

Why does `getEntities()` return an empty array here? If this were javascript, I'd think that the array is being populated concurrently and this line is executing too early, but java executes lines sequentially... right?

**Comment by BrianErikson** [comment]
Pushed a fix. We were adding entities to a queue and then adding them to the real scene list at the end of each frame, but really we only need to do so for pending entity removals.
