### ISSUE TITLE
Dyn4j accuracy low with large scenes

### ISSUE THREAD

**Issue by BrianErikson** [EmergentOrganization/cell-rpg#24]
Unfortunately I think we have to bend to dyn4j's will and implement a chunk strategy in both map creation and loading schemes. If you wish to see what the problem is, please checkout branch `dyn4jBroke` and run into the building to see what I'm talking about

**Comment by BrianErikson** [comment]
Oh also it would be a good idea to restrict the max width and max height for each scene to 7500x7500px. OR we could also scale everything way down and zoom in the camera so that dyn4j has plenty of integers to work with.

**Comment by 7yl4r** [comment]
don't ask me how I lost the commit for this, but things are scaled down 1:10 as of e46f2497f0de4ab91fa64afc45633727541f91ad

**Comment by BrianErikson** [comment]
fixed with commit c7f9381ece5813f786089070170c3fa44f4c9436
