### ISSUE TITLE
SVG Map coordinate parsing weirdness

### ISSUE THREAD

**Issue by BrianErikson** [EmergentOrganization/cell-rpg#25]
![image](https://cloud.githubusercontent.com/assets/7645647/8144427/f2770352-11de-11e5-8e60-1b93bb746326.png)

![image](https://cloud.githubusercontent.com/assets/7645647/8144417/ad0d70e4-11de-11e5-9d39-8618aaefcd93.png)

```
[MapLoader] Parsing map testMap.svg
[MapLoader] Importing layer: backgrounds with group offset [0.0:-452.3622]
[MapLoader] Importing layer: buildingsAndScenery with group offset [0.0:-5400.0]
[MapLoader] Importing layer: chars with group offset [0.0:-5400.0]
[Map] Loading THE_EDGE at pos:[400.1092:130.29843]
[Map] Loading BUILDING_LARGE_1 at pos:[620.8541:308.5088]
[Map] Loading BUILDING_ROUND_1 at pos:[2528.7634:-325.4287]
[Map] Loading BUILDING_LARGE_1 at pos:[-315.8439:54.103027]
[Map] Loading BUILDING_ROUND_1 at pos:[-239.30556:73.82471]
[Map] Loading BUILDING_LARGE_1 at pos:[620.8673:-11098.434]
[Map] Loading BUILDING_ROUND_1 at pos:[-1807.1687:26.24707]
[Map] Loading BUILDING_ROUND_1 at pos:[1368.1367:184.43555]
[Map] Loading CHAR_CIV1_BLINKER at pos:[-301.24417:343.4961]
[Map] Loading CHAR_CIV1_BLINKER at pos:[638.81067:391.88135]
[Map] Loading CHAR_PLAYER at pos:[583.2189:295.75342]
```

What gives? I need some help with this Inkscape coordinate weirdness

**Comment by 7yl4r** [comment]
It looks like the layers themselves (which are actually treated as groups) got translated in this most recent version.

``` svg
  <g
     inkscape:groupmode="layer"
     id="layer4"
     inkscape:label="buildingsAndScenery"
     style="display:inline"
     transform="translate(0,-5400)"
     sodipodi:insensitive="true">
    <image
       y="5708.5088"
       x="620.85413"
       id="image7413"
       xlink:href="file:///home/tylar/cell-rpg/android/assets/building-large-1.png"
       height="100"
       width="61.099998" />

...

</g>
```

I think I know how this happened and may be able to fix it in the svg if it's a pain to read the layer `<g>`'s `transform` and interpret children relative to that. I don't think this is going to be a common thing; I think it is a result of me scaling down the whole svg and then re-positioning.

**Comment by 7yl4r** [comment]
ed9c6da removes the transforms from the group-layers, but now has translate transforms applied on the individual elements. I don't know why inkscape has decided to do that rather than just modify x and y values; I think it has something to do with copy/pasting rather than creating new objects. 

This is also manually fixable, but this could be a more common problem than the group-layer transform so we may want to consider dealing with it in code or maybe even writing a script that cleans up these silly translate transforms on singlular objects in the svg file.

**Comment by 7yl4r** [comment]
Still seems broken. Perhaps the transforms aren't being applied properly?

**Comment by BrianErikson** [comment]
The transforms were being applied on a group basis, so I'll have to amend it to operate on a per-item basis

**Comment by 7yl4r** [comment]
oh, I see. Yeah, there were transforms on both groups and items, and now it should just be on individual items.

**Comment by BrianErikson** [comment]
I've done that, but there's something still really off about how inkscape handles rotations. 

Here's the XML code for the two large buildings that are inverted from each other in the SVG file:

```
<image
   transform="translate(0,-5400)" // This is offset due to relative coords in inkscape. is fine.
   style="display:inline"
   y="5708.5088"
   x="620.85413"
   id="image7413"
   xlink:href="file:///home/tylar/cell-rpg/android/assets/building-large-1.png"
   height="100"
   width="61.099998" />

<image
   style="display:inline"
   y="-5698.4341" // <--- STRANGE! It must be due to being inverted
   x="620.86731"
   id="image7413-1"
   xlink:href="file:///home/tylar/cell-rpg/android/assets/building-large-1.png"
   height="100"
   width="61.099998"
   transform="matrix(1,0,0,-1,0,-5400)" /> // This is the inverted building
```

I haven't figured out how to handle all of these use-cases. It also appears to rotate objects from the center of the object, whereas the origin in our game is the bottom-left corner of the object. I'm about to throw in the towel and just roll my own version ^^

**Comment by 7yl4r** [comment]
Wow, that does look pretty bizarre. I guess the transform is applied before
placing the object? So that negative y value is like a mathematical
double-negative? :/

This is getting crazy enough that I'm starting to wonder if we should open
up an issue with inkscape.

**Comment by BrianErikson** [comment]
Well, what you says makes sense in a mathematical way, but translation vectors in transforms are additive, not subtractive. We could make a special exception, `if y is < 0 then invert` but that would mean we could never go negative on the y-axis, which would just be a nasty hack.

**Comment by BrianErikson** [comment]
Bypassed due to implementing our own map editor
