### ISSUE TITLE
CA-grid component

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#3]
![eg](https://files.gitter.im/EmergentOrganization/cell-rpg/OOub/thumb/Untitled.png)

[Original size](https://files.gitter.im/EmergentOrganization/cell-rpg/OOub/Untitled.png)

**Comment by BrianErikson** [comment]
@7yl4r hmm, I'm not sure anyone can read that :see_no_evil:

**Comment by 7yl4r** [comment]
Oh, must've got resized when pasted it from gitter. @InfiniteSearchSpace should have the original, or you may be able to track it down in the chat

**Comment by BrianErikson** [comment]
Is there any source code that we could review so we can get the ball rolling on this? :santa:

**Comment by orelb** [comment]
I added the original link.

**Comment by InfiniteSearchSpace** [comment]
I was spitballing a bit here, I don't really understand if this is an appropriate way of approaching the issue. Anyone have any thoughts on it?

**Comment by 7yl4r** [comment]
I think we're going to want to approach the addition of CAs to this game in a few different ways, and I think this will need to be one of them. Don't worry about building out a full CA engine or anything though. We just need prototypes to play around with at this stage I think.

**Comment by 7yl4r** [comment]
This issue and approach are a bit out-of-date so I'm closing this for now and will re-open issues with more specific tasks in the future.
