### ISSUE TITLE
pause/inventory/map menu

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#31]
in-game menu to display a map, inventory, settings, and maybe a few other tidbits is needed. I'm unsure whether or not this should pause the game. I'm imagining it something like ![this](http://oi42.tinypic.com/k0q715.jpg), but of course we could be much more creative with it.

**Comment by BrianErikson** [comment]
Added the [pause functionality](https://github.com/EmergentOrganization/cell-rpg/blob/ab1aee30310ed5c611baa30bc87a640844e4fdbd/core/src/com/emergentorganization/cellrpg/scenes/PausableScene.java). Leaving this open for someone to hook in and design UI for it
