### ISSUE TITLE
Entity/component docs

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#35]
The number of entities and components is steadily increasing and I'm starting to lose track of what each thing does and requires. Maybe it is better we start on the documentation as early as possible for Entities and components?

For components in particular I think we may need a dependency grid. Thoughts?

**Comment by BrianErikson** [comment]
Added a wiki entry for [Component Dependencies](https://github.com/EmergentOrganization/cell-rpg/wiki/Component-Dependency-Matrix). Let me know what you think.

**Comment by 7yl4r** [comment]
That looks good, is there any other low-hanging documentation fruit or should we close this for now?

The only other thing I can think of is to expand on docstrings / class desc comments. I'd like to have short descriptions for reference in one place, but that would be too hard to maintain as a wiki page. Ideally we could pull those into documentation but I don't know how to do that in java.
