### ISSUE TITLE
The Big Ol' Asset thread

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#37]
There's a good collection of reference imagery in the /art/ directory, but what about open assets we could just drop right in game with minimal tweaking? Post those here and I should be able to get them in ASAP. 

NOTE: Please ensure the license allows for us to use them with modification!

**Comment by 7yl4r** [comment]
[2d abstract jungle sprites might be useful for scenery/plants with some modification](http://opengameart.org/content/jungle-sideview):

![sample](http://opengameart.org/sites/default/files/styles/medium/public/preview_206.png)

**Comment by 7yl4r** [comment]
abstract dark backgrounds for area background tiles:
[one](http://opengameart.org/content/generated-backgrounds-vol-2-1074x768)
[two](http://opengameart.org/content/generated-backgrounds-vol-1-800x600)

![sample](http://opengameart.org/sites/default/files/styles/medium/public/vol2sample.jpg)

**Comment by 7yl4r** [comment]
Millionth Vector's top-down space stations/ships from various factions. 

![sample](http://opengameart.org/content/set-faction10-spacestations)

Lots here which could be easily adapted to fit, and with faction differences already baked in! I don't think we will have "ships", but I'm thinking these can be pieced together or broken apart to create buildings.
- [f10 stations](http://opengameart.org/content/set-faction10-spacestations)
- [f9 stations](http://opengameart.org/content/set-faction9-spacestations)
- [f9 ships](http://opengameart.org/content/set-faction9-spaceships)

much more... (see user [Bonsaiheldin](http://opengameart.org/users/bonsaiheldin))

or... even better: view the [free sprites page(s) on Millionth Vector](http://millionthvector.blogspot.de/p/free-sprites.html)

**Comment by BrianErikson** [comment]
Ported over to trello
