### ISSUE TITLE
Wall/shield CA

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#38]
I'd like to identify some kind of CA which allow us to create a flame/energy wall along the edge of certain buildings.

![like this](http://www.lachlandean.com/blog/wp-content/uploads/2014/02/fireLine.gif)

I think this may be doable by seeding state 3 along the wall and setting up the rules to transition 3->2->1->0 if same-state neighbor count is < 7ish

Can someone help me describe this better?

**Comment by BrianErikson** [comment]
Ported to trello
