### ISSUE TITLE
weapon charge display on character

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#41]
![mockup](http://i.imgur.com/FtHZBBr.png)

**Comment by BrianErikson** [comment]
+1 from me

**Comment by 7yl4r** [comment]
more visible at character size: 

![ammo-demo](https://cloud.githubusercontent.com/assets/1051390/9835268/57af9f68-59b0-11e5-83b4-cb88c065f078.png)
