### ISSUE TITLE
basic sounds for arcade shooter

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#42]
sounds needed:

player:
- shield fully charged (notification)
- shield critical warning sound (looped)
- shield damaged from collision with CA

base weapon:
- energy shot fired
- energy shot collided with CA, destroys CA in radius (explosion-like?)
- out of ammo sound

music:
- ambient space-shooter track on loop (or hey, procedurally generate it using CA like [wolframTones](http://tones.wolfram.com/), why not?)

UI
- button click or keypress event

**Comment by 7yl4r** [comment]
uh oh, [another link with more information on CA-music](http://www.ibm.com/developerworks/java/library/j-camusic/). I'm trying really hard not to get distracted and end up writing a procedural music library, but it's looking more and more tempting.

**Comment by 7yl4r** [comment]
oop, one more: [CAMUS](http://tamw.atari-users.net/camus.htm)

**Comment by 7yl4r** [comment]
[JFugue](http://www.jfugue.org/examples.html) looks like it could make procedural, CA-generated music that much easier...

**Comment by 7yl4r** [comment]
I couldn't resist... Now exploring generative music using CA [in this repo](https://github.com/Sciguymjm/CellularAutomata).

**Comment by 7yl4r** [comment]
I'm finding a really surprisingly large body of existing work in the area of [generative](https://github.com/Sciguymjm/CellularAutomata/wiki) and adaptive music for games. [FMOD](http://www.fmod.org/) even seems to have a slew of commercial-level tools for this kind of thing free of cost (for indie devs). [Here's a nice demo of how FMOD Studio works.](https://www.youtube.com/watch?v=tW08YWvb3vU)

**Comment by BrianErikson** [comment]
We might want to get some basic sounds and a simple background track in there for the first public alpha -- people will definitely notice the lack of sound effects, and that might detract from other useful critiquing

**Comment by 7yl4r** [comment]
libgdx + fmod links for later reference
- http://www.java-gaming.org/index.php?topic=36081.0
- http://astrangergravity.com/binding-to-fmod/

**Comment by BrianErikson** [comment]
This issue is basically resolved for now -- we are triggering sounds based on an event system. The background music generation should probably be a different issue
