### ISSUE TITLE
set up versioning (using gradle?)

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#46]
I'd like to be able to manually assign a semantic version number as we progress, and having a versionCode will also be important for pushing updates. Has anyone used gradle to do this before? I think [this looks like a pretty good method](http://bryankrosenbaum.com/2013/11/27/getting-to-know-gradle-auto-increment-version-and-signing-releases/) to go about it, but I have no experience here and I don't 100% understand all that is going on there.

**Comment by BrianErikson** [comment]
Is gradle necessary? We could probably just manually increment the version in code somewhere when something drastic changes like file I/O or network operations

**Comment by 7yl4r** [comment]
No, I don't think it is. I'd actually prefer to increment the version number manually. But I think the right place to keep it is in the gradle file, and I'm not sure how to set up the android versioning alongside.

**Comment by 7yl4r** [comment]
Is [this line](https://github.com/EmergentOrganization/cell-rpg/blob/master/build.gradle#L18) referring to our project's version? I can't tell...

**Comment by BrianErikson** [comment]
According to [this StackOverflow post](http://stackoverflow.com/a/17263028), it looks like you're correct. There's a few other options we have as well it looks like

I'm not sure what happens when build versions don't match, though

**Comment by 7yl4r** [comment]
I saw that post when I was first thinking about this, but couldn't figure out what they were talking about. o.O I'm trying to find out how I might read in that version number in java and then display it on the main menu. I thought this would be easy and well-documented so I could get more acquainted with gradle versioning, but can't find anything useful.

**Comment by BrianErikson** [comment]
I don't think gradle interacts with Java in any way, since Java doesn't have a preprocessor. I still think the most simple solution would to put a `public static final float VERSION = 0.1f` in the `CellRPG` class. That way you can reference it by `CellRPG.VERSION`

**Comment by 7yl4r** [comment]
I'm sure we'll have to revisit this once we start doing actual releases, but for now feel free to bump the "minor" or "patch" numbers manually whenever you see fit. The "patch" can be bumped as often as every commit, but I'm sure it will get forgotten sometimes (and that's no problem).

[This description of semantic versioning](http://semver.org/) doesn't quite fit our purposes (since we have no API nor backwards-compatibility concerns) so I think of it more like this for games:

MAJOR.MINOR.PATCH
- MAJOR = release or other large, multi-feature milestone marker.
- MINOR = mini-milestone indicating completion of feature-set or dev goal met. 
- PATCH = individual improvements, features, bug-fixes, etc.

I'm starting us off at 0.1.0, our previous work on the engine can be called 0.0.*, and the release of the arcade version will be 1.0.0.

Oh! and one last thing: only bump version numbers on the master branch (else things could get weird).
