### ISSUE TITLE
basic player movement

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#5]
add movement to the player.

A click on the screen should set a visible waypoint which the player travels towards, the camera should remain centered on the player.

**Comment by orelb** [comment]
Basic movement is done. I only have to add the visible waypoint.

**Comment by BrianErikson** [comment]
@orelbitton We may want to alter the behavior a bit so that even when you release the mouse, the player still goes to the last-clicked position. I believe that's what the visible waypoint was intended for

**Comment by orelb** [comment]
@BrianErikson Done. It's only local positions though, when we will implement the world I'll have to change it a bit.

**Comment by 7yl4r** [comment]
closed by 0a55fc347ada892e1fae617faeb9415013985fb6
