### ISSUE TITLE
mapEditor: can't select new buildings

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#53]
for rift1 and vyroid-generator, I can't seem to select the buildings to move them after I have added them to the map.

All I did to add them to the mapEditor was to add them to EntityList.java, I suspect there is some other step I missed?

They do have collision json objects defined using the box2d-physics-body-editor saved to /data/colliderProject.

**Comment by 7yl4r** [comment]
To be even more specific: I followed the steps I just put up on [this wiki page](https://github.com/EmergentOrganization/cell-rpg/wiki/Entity-creation-guide) for creating collide-able and mapEditor Entities. Please update if I missed something.

**Comment by BrianErikson** [comment]
I enabled the debug renderer for the physics object hooked into VyroidGenerator, and it seems that the collider was parsed wrong or something: 

![screenshot from 2015-09-13 08 05 11](https://cloud.githubusercontent.com/assets/7645647/9835479/5727f64c-59ee-11e5-977f-92ea967f9431.png)

**Comment by 7yl4r** [comment]
I did draw a temporary collider around just the cloud to test it out, but
even that wasn't interacting properly.

The bounding box looks right, but the collider definitely shouldn't be way over there.
