### ISSUE TITLE
mapEditor undo

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#54]
Having a full undo/redo would be useful of course, but just a simple 1 or 2-step undo would help out a lot for when I accidentally move the wrong thing.

**Comment by BrianErikson** [comment]
Progress is being made on the editorUndo branch... Slowly. I sense a lot of refactoring in my future

**Comment by 7yl4r** [comment]
I figured this one would cause some trouble. It's not critical, but I would be very grateful to have it.

**Comment by BrianErikson** [comment]
ported over to trello
