### ISSUE TITLE
Profiler opens multiple instances

### ISSUE THREAD

**Issue by BrianErikson** [EmergentOrganization/cell-rpg#58]
When switching between menus and scenes, the profiler 'stacks'.
![screenshot from 2015-09-13 07 32 16](https://cloud.githubusercontent.com/assets/7645647/9835404/a84c3a24-59e9-11e5-8d88-4cbe5ba8c559.png)

**Comment by 7yl4r** [comment]
This is probably related to scenes not deconstructing properly. You can notice a memory leak too if you open and exit a scene several times; memory usage only ever goes up. (using system performance monitor)

**Comment by BrianErikson** [comment]
I cleaned up all obvious memory leaks in the program AFAIK. I'm going to go ahead and close this for now
