### ISSUE TITLE
mapEditor: occasionally can't zoom in/out

### ISSUE THREAD

**Issue by BrianErikson** [EmergentOrganization/cell-rpg#59]

**Comment by 7yl4r** [comment]
I noticed this too. One time it seemed that I couldn't zoom using scroll, but could zoom using z/x. The other time I had the opposite issue. I haven't yet had both broken simultaneously though.

**Comment by BrianErikson** [comment]
It seems that if you scroll the list in the import/export menus, the focus will remain there, even after you close out of the menu.
