### ISSUE TITLE
shield particle effect 

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#60]
![img](http://cdn.makeagif.com/media/9-13-2015/clflAp.gif)

**Comment by BrianErikson** [comment]
We may even want to entirely replace the texture with this effect, and reduce the emissions as it gets damaged. As the game matures, the shield texture is looking more and more out of place

**Comment by 7yl4r** [comment]
Yeah, I think I agree. The particle effect could take over completely if
done right.

**Comment by BrianErikson** [comment]
ported over to trello
