### ISSUE TITLE
devMode toggle

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#62]
we need to "turn off" or else remove dev features in the release. We could have "release branch" in which we can remove dev features, else we need to set up some way of toggling on "devMode" after starting up the game. 

devMode features not included in release of v1:
- story-mode on main menu (perhaps replace with "coming soon?")
- profiler HUD

Thoughts?

**Comment by BrianErikson** [comment]
I'm going to claim a bit of this and write a class to read and write to a `config.txt` file so we can toggle it there

**Comment by BrianErikson** [comment]
I ended up using `Gdx.App.Preferences` for the cross-platform compatibility. Use `CellRpg.fetch().isDevModeEnabled()` to get the state.

We still need to put this to use and show/hide things depending on the state though, so I'll leave this open for now
