### ISSUE TITLE
Use Lombok to reduce clutter

### ISSUE THREAD

**Issue by BrianErikson** [EmergentOrganization/cell-rpg#66]
Never used it in a project before, but [this usage](https://github.com/cxxr/better-java#lombok) looks phenomenal. I've always been bothered by getters/setters.

What do you guys think?

**Comment by 7yl4r** [comment]
I spent wayyy too long reading through all of that and continuously having my mind blown. I'm willing to give it a shot if you are.

**Comment by BrianErikson** [comment]
I'm having way too many build problems between Android and HTML -- unless we have a gradle-fu master around here, I don't think it's going to happen unfortunately
