### ISSUE TITLE
player location seems to jolt around randomly

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#67]
noticed in arcade mode using wasd+mouse controls, the player's location will randomly jolt. Noticed this nearly every time I played.

**Comment by BrianErikson** [comment]
Interesting -- I haven't seen this. Is it only associated with arcade mode?

**Comment by 7yl4r** [comment]
I'm not sure. I can't seem to reproduce it today. Perhaps this was resolved on the master branch and I was seeing it from some older code on cellRevamp

**Comment by 7yl4r** [comment]
Ah. I think I have an idea what this is. It may be a side-effect of how I'm adding the vyroidGenerators to the arcadeScene. They are added as very small so they are not visible, but I think the colliers may still be interacting occasionally, despite being very small.
