### ISSUE TITLE
game crash on shield down

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#68]
I've noticed that the game will crash and throw a rather strange error: 
`Exception in thread "LWJGL Application" org.lwjgl.opengl.OpenGLException: Cannot use offsets when Array Buffer Object is disabled`

After some googling, the best I can figure is that this error is [the result of some improper disposal](http://stackoverflow.com/questions/17005585/array-buffer-object-is-disabled).

I believe this error is fairly new, as I did not notice it before cellRevamp. 

To reproduce connect to a arcade or story game and run into CA until the shield is fully depleted.

**Comment by 7yl4r** [comment]
What is particularly interesting about this bug is that the same code seems to be used in `Player` (which causes the crash) seems to be nearly identical to the pause menu's exit in `PausableScene`.

**Comment by BrianErikson** [comment]
It has something to do with the fact that the stack that calls `Scene.Dispose()` is part of the render stack, because you can't dispose of resources that are already being used. Ironically though, when you set up the disposal to happen at the end of the frame, the actual scene doesn't swap to the main menu, and just results in a black screen. Not sure what the fix is for this

**Comment by 7yl4r** [comment]
bbbdf48 got us past that last enigmatic crash by postponing the `dispose()` call with a timer, but it's still there... if in a slightly different form: `RuntimeException: No OpenGL context found in the current thread.`

This patch makes the error a bit less critical, but this definitely still needs fixing, and I'm not much closer to understanding how.

**Comment by 7yl4r** [comment]
I've found that this error first showed up in cba4c5287a0c1912a4c7d4bf7f69cd04b1d1ae05, and have verified that it is [the scene disposal](https://github.com/EmergentOrganization/cell-rpg/commit/cba4c5287a0c1912a4c7d4bf7f69cd04b1d1ae05#diff-edbb7e6944c7b3e3abceb0e225a05aafR63). This makes sense and doesn't help much. I'll need to read up more on how to properly dispose these various components used in the scene

**Comment by 7yl4r** [comment]
according to this log I just produced, it seems that scene.render() is being called after disposing is complete.

```
[INFO]  15:35:43.082    scenes.ArcadeScene.render   -   debugRender using com.badlogic.gdx.graphics.glutils.ShapeRenderer@264c9375
[INFO]  15:35:43.107    scenes.ArcadeScene.render   -   debugRender using com.badlogic.gdx.graphics.glutils.ShapeRenderer@264c9375
[INFO]  15:35:43.131    characters.Player.fireEvent -   game over
[INFO]  15:35:43.132    mainmenu.MainMenu.create    -   Creating scene
[INFO]  15:35:43.148    mainmenu.MainMenu.create    -   init game camera 102.4x75.0
[INFO]  15:35:43.148    mainmenu.MainMenu.create    -   parsing external physics meshes
[INFO]  15:35:43.149    scenes.ArcadeScene.dispose  -   disposing scene
[INFO]  15:35:43.149    scenes.ArcadeScene.removeEntity -   removing entity class com.emergentorganization.cellrpg.entities.buildings.VyroidGenEntity
[INFO]  15:35:43.150    scenes.ArcadeScene.removeEntity -   removing entity class com.emergentorganization.cellrpg.entities.buildings.VyroidGenEntity
[INFO]  15:35:43.150    scenes.ArcadeScene.removeEntity -   removing entity class com.emergentorganization.cellrpg.entities.FollowingCamera
[INFO]  15:35:43.150    scenes.ArcadeScene.removeEntity -   removing entity class com.emergentorganization.cellrpg.entities.buildings.VyroidGenEntity
[INFO]  15:35:43.150    scenes.ArcadeScene.removeEntity -   removing entity class com.emergentorganization.cellrpg.entities.buildings.VyroidGenEntity
[INFO]  15:35:43.150    scenes.ArcadeScene.removeEntity -   removing entity class com.emergentorganization.cellrpg.entities.WeaponPowerup
[INFO]  15:35:43.150    scenes.ArcadeScene.removeEntity -   removing entity class com.emergentorganization.cellrpg.entities.ShieldPowerup
[INFO]  15:35:43.150    scenes.ArcadeScene.removeEntity -   removing entity class com.emergentorganization.cellrpg.entities.WeaponPowerup
[INFO]  15:35:43.150    scenes.ArcadeScene.removeEntity -   removing entity class com.emergentorganization.cellrpg.entities.ShieldPowerup
[INFO]  15:35:43.150    scenes.ArcadeScene.removeEntity -   removing entity class com.emergentorganization.cellrpg.entities.WeaponPowerup
[INFO]  15:35:43.150    scenes.ArcadeScene.removeEntity -   removing entity class com.emergentorganization.cellrpg.entities.ShieldPowerup
[INFO]  15:35:43.150    scenes.ArcadeScene.removeEntity -   removing entity class com.emergentorganization.cellrpg.entities.characters.Player
[INFO]  15:35:43.150    scenes.ArcadeScene.removeEntity -   removing entity class com.emergentorganization.cellrpg.entities.ca.BufferedCAGrid
[INFO]  15:35:43.150    scenes.ArcadeScene.removeEntity -   removing entity class com.emergentorganization.cellrpg.entities.ca.BufferedCAGrid
[INFO]  15:35:43.150    scenes.ArcadeScene.removeEntity -   removing entity class com.emergentorganization.cellrpg.entities.ca.BufferedCAGrid
[INFO]  15:35:43.151    scenes.ArcadeScene.removeEntity -   removing entity class com.emergentorganization.cellrpg.entities.ca.NoBufferCAGrid
[INFO]  15:35:43.151    scenes.ArcadeScene.removeEntity -   removing entity class com.emergentorganization.cellrpg.entities.ScoreHUD
[INFO]  15:35:43.152    scenes.ArcadeScene.dispose  -   scene disposed.
[INFO]  15:35:43.153    scenes.ArcadeScene.render   -   debugRender using com.badlogic.gdx.graphics.glutils.ShapeRenderer@264c9375
Exception in thread "LWJGL Application" org.lwjgl.opengl.OpenGLException: Cannot use offsets when Array Buffer Object is disabled
```

**Comment by 7yl4r** [comment]
Oops. did not intend to close this. I'm not comfortable closing it until I am more certain that the scene is getting disposed.

**Comment by BrianErikson** [comment]
@7yl4r verify 7a405d8 works when you get the chance. I can't believe I hadn't thought of doing this way before -- I guess it's only obvious in hindsight.

**Comment by 7yl4r** [comment]
Ah, that 7a405d8 looks much better than my hack. Looks like it's working to me too. I spent way too much time trying to track down the cause of those errors.
