### ISSUE TITLE
particle effects pool

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#70]
Particle effects should be pooled for efficiency, but this doesn't jive well with the scene-entity paradigm. Therefore, what is probably needed is for some particle effect helper on the scene which stores persistent particle effect pools that entities can use to trigger particle effects.

Though this isn't mandatory, the performance improvements over constructing/deconstructing particle effects for each entity combined with the relatively small additional work to take this extra step mean that this issue should probably preclude implementation of particles effects like #60, #61, and #63.

For example code see [this video](https://youtu.be/3OwIiELYa70?t=2477) and [in this SO answer](http://stackoverflow.com/a/18421382/1483986)

**Comment by BrianErikson** [comment]
Ported over to trello
