### ISSUE TITLE
some methods unaffected by pausing

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#74]
For instance, startup an arcade-mode session and leave it paused for a while. When you unpause, you'll find that many powerups (and vyroid generators) were placed while the game was paused. CA generations also proceed while paused. 

I guess the solution here is to check scene.isPaused() or similar for update() methods that should pause? Or maybe there is a way we can keep update() from being called on a scene's entities?

**Comment by BrianErikson** [comment]
All pausing behaviors working now (as far as I know)
