### ISSUE TITLE
"levels" in arcade mode

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#76]
Based on [feedback from /u/ketura](https://www.reddit.com/r/gamedev/comments/3mk0nl/its_the_rgamedev_daily_random_discussion_thread/cvgkgs6) perhaps we should break arcade mode's escalation into levels which can be "won" by (one of):
1. defeating a certain # of vyroids, 
2. clearing the area of vyroids, 
3. collecting a number of powerups, 
4. surviving an allotted time.

This would also let us add a bit of story or explanation between levels. Thoughts?

**Comment by BrianErikson** [comment]
I think a more structured goal to progress would be similar to how [Geometry Wars](https://www.youtube.com/watch?v=y-_qlaywKBs) does it; a sequence of spawn-events in each level that up the intensity. We could also derive the nuke from Geometry Wars and apply that into our game as well; it serves as a limited 'panic button' and kills everything currently on the screen.

**Comment by 7yl4r** [comment]
I have a few 100 hrs of geometry wars play under my belt, and loved every minute of it. I definitely want to draw a lot of inspiration from their visual/audio effects, but hadn't though of it with regards to leveling. It is interesting how different waves are apparent without being entirely separate... maybe that is better than stopping the action for a score breakdown.

**Comment by 7yl4r** [comment]
spawn-events in arcade mode implemented. We could use a few more levels and some balancing, but the basic principal is there! :tada:
