### ISSUE TITLE
player weapon

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#8]
implement simple player weapon which shoots out lasers/bullets. Use an temporary sprite or shape for the bullets. Collisions not yet required.

Weapon should be fired by clicking. Yes, this does mean that shooting and moving are the same; we're planning to fix this later by interpreting the context around the click point.

**Comment by orelb** [comment]
@7yl4r For mobiles, we can use [TouchPad](http://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/scenes/scene2d/ui/Touchpad.html)
On desktop, the movement can be done by WASD, shooting by mouse. Or using a key to shoot towards the mouse.

**Comment by 7yl4r** [comment]
I agree with you for the desktop, but for mobile I want to try something different.

We had a discussion about controls on mobile a little while back and decided we didn't really want to use some common things and here is why:
- touch-screen joystick : tends to get lost or off-center under thumb b/c no tactile feedback
- on-screen buttons for shooting/moving : same problems as joystick
- accelerometer-based-controls : device-dependent and annoying in general

Here's a few solutions we came up with:
1. tap to shoot, long tap to move
2. tap to shoot, long tap to set waypoint, swipe to "bump" movement (for quick reactions)
3. tap to shoot and move, only shoot sometimes by examining tap location

I'd love to discuss more ideas, but after pretending to play on my phone I think 2 or 3 is the best so far.

**Comment by 7yl4r** [comment]
Here's a new one: 

4.) tap to shoot, click & drag to draw path for player to follow (this makes walking long distances nicer)

**Comment by BrianErikson** [comment]
@7yl4r, I'm liking 4). That way we can avoid pathing algorithms

**Comment by orelb** [comment]
A quick click or a touch makes the player shoot a Bullet entity. 

In the future we might want to add a Weapon class to be able to customize the bullets / shooting rate.
