### ISSUE TITLE
basic usage analytics 

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#80]
I'd like to add some basic tracking to the app before releasing, and there are two things which need to be addressed:
1. what questions do we have that might be answered with analytics?
2. what analytics software should we use?

Here are my ideas for (1):
- at what point to people quit the game and not play any more?
- what config options do player prefer?
- what weapon powerups do players seem to prefer?
- what weapon powerups lead to the highest score increase?
- what is the distribution of player scores?
- what options/configs result in higher scores?
- what performance level is the game being run at?
- host demographics (OS, memory, graphics, etc)

For (2), we have a myriad of (free) options, my two favorites are:
- Count.ly : b/c I've used it before and liked it
- Google Analytics : b/c of widespread use 

Have you used anything like this before @BrianErikson ?

**Comment by 7yl4r** [comment]
countly & google analytics support on java is weak (they both focus on android mostly). There are some 3rd party libraries for google analytics, and a usable REST interface for countly, but I've also found the [mixpanel java API documentation](https://mixpanel.com/help/reference/java) quite beautiful. Because of this, I'm leaning towards mixpanel currently.

**Comment by BrianErikson** [comment]
I've never used Mixpanel but it looks perfect to me
