### ISSUE TITLE
Arcade mode is too easy

### ISSUE THREAD

**Issue by BrianErikson** [EmergentOrganization/cell-rpg#82]
Largely because of a small player hit-box, the arcade mode is too easy.
- Increase player hit box to the 95% of it's shield (for close call thrills)
- Increase size of smallest CA layer
  - Too easy to dodge -- more of a small hindrance to the player rather than a challenge

Anyone else have other ideas?

**Comment by 7yl4r** [comment]
I agree about the hit box. I've also noticed that not moving at all is
super effective; that may actually be a bug.

Another way to make it more difficult is to choose a more aggressive (or
higher density) CA rule. I've looked at a few, but I was hoping
@infinitesearchspace might be able to help out with this aspect.

One ruleset that comes to mind is highLife, which looks a lot like CGoL,
but I'll do some more searching.

**Comment by BrianErikson** [comment]
This is less of an issue now
