### ISSUE TITLE
onDamage gamefeel++

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#83]
There are a few different visual things we could do to make bumping into vyroids feel more damaging.
- chromatic aberration
- screen shake
- "shockwave" displacement map
- particle effect (on the shield)

I think I can add the particle effect without too much problem, but do we want to try out some of these others? I think screen shake won't be too difficult, but I'm not sure about the others. [Here's a video showing each for reference.](https://youtu.be/pmSAG51BybY?t=1050)

**Comment by BrianErikson** [comment]
ported over to trello
