### ISSUE TITLE
Artemis Conversion Tracker

### ISSUE THREAD

**Issue by BrianErikson** [EmergentOrganization/cell-rpg#86]
_Because crossing things off is fun_
# Entity
- Characters
  - Player
    - Input
      - ~~Weapons~~
        - ~~Shooting~~
      - Android
      - ~~Desktop~~
    - ~~Shield~~
  - Civ1Blinker
    - ~~Import~~
    - Pathing
- ~~Backgrounds~~
  - ~~The Edge~~
- Buildings
  - ~~BuildingLarge1~~
  - BuildingRound1
    - ~~Import~~
    - CA Functionality?
  - ~~Rift1~~
  - ~~Rift2~~
  - VyroidBeacon
    - ~~Import~~
    - CA Functionality?
  - VyroidGenEntity
# Cellular Automata
- Damage Player
- Damage by Weapon
- CA Grid
  - Scaled properly
  - Rendering System
# Scene
- ~~Scene Transition Handling~~
  - ~~Transition between scenes~~
  - ~~Properly dispose of old scenes during transition~~
- ~~Main Menu~~
- ~~Settings~~
- ~~General Functionality~~
  - ~~Pause menu~~
    - ~~Trigger by ESC~~
    - ~~Change Controls~~ _Out of scope_
    - ~~Change camera params~~
- Arcade
  - Accrue points
  - World boundaries for player
- ~~Story Mode~~
  - ~~Import JSON map~~
# Effects
- ~~Render in layers~~
- ~~Batched Shader Rendering~~
  - ~~Glow Shader~~
- Bullet Trail
- Power-ups
- Background Music
- ~~Sound effects~~
  - ~~Player shooting~~
  - ~~Player damaged~~
  - ~~CA damaged~~
  - ~~Power-up pickup~~
  - ~~Win~~
  - ~~Lose~~
# Events
- ~~Player shooting~~
- ~~Player damaged~~
- CA damaged
- Power-up pickup
- Win
- ~~Lose~~
- ~~Shield states/loss~~
# ~~Physics~~
- ~~Buildings ignore other buildings~~ _Box2D doesn't care if statics overlap_
- ~~Player collides with objects cleanly~~
- ~~Mesh importing from aurelienribon tool~~
# ~~Tools~~
- ~~JSON map importing~~
- ~~Map Editor~~
  - ~~Box2D functionality conversion~~
  - ~~Select objects without a collider~~
# Misc
- Dialogs

**Comment by BrianErikson** [comment]
Feel free to leave any notes or edit it as needed

**Comment by 7yl4r** [comment]
I'm still feeling unsure where to start here. Can you help me identify an easy entry-point? Or maybe a good example old/new class to compare? The ones I've looked at so far seem to have little code in common.

**Comment by BrianErikson** [comment]
Due to the way that Artemis works, the way scenes were working needed to be nixed, as well as how we were doing entity/components. Because of this, the only code that will largely appear the same would be the internal workings of the CA generation (only part that would need to be changed would be how it is rendered). 

This is a bit off-topic, but I'm actually a huge fan of the way artemis works, and it opened my eyes to how much cleaner you can make the code due to the unique use of systems/components. You can basically add a component to an entity as a tag of sorts, which will then allow that entity's components to be processed by certain systems. Most of the gameplay logic will be systems that process entities (bags of components). When you get a minute to chat sometime, you can grill me and I can explain how everything works over gitter.

**Comment by 7yl4r** [comment]
:+1:

**Comment by BrianErikson** [comment]
We're actually almost done now! All that's left is android input support, CA integration + interaction (player shield, damage, death, etc), sounds, and a few other small odds and ends :). I'm surprised how smoothly it's going so far

**Comment by BrianErikson** [comment]
Instead of allowing "Control Options", we might just want to allow keybinding for the desktop version, and just hide it for the (more technical) android controls. Just a thought

**Comment by BrianErikson** [comment]
Artemis branch has been merged
