### ISSUE TITLE
CA render on top of pause menu

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#89]
![image](https://cloud.githubusercontent.com/assets/1051390/12066497/94e7dac4-afb6-11e5-90c7-9f41bd8942ac.png)

**Comment by BrianErikson** [comment]
Check the way the systems are ordered when creating the World Configuration - - the CaRenderer is probably added after the window one is

**Comment by 7yl4r** [comment]
I think the problem here is that the CA keep generating and rendering even when paused. It might be a bit tricky to fix that, since the CA each have their own thread.

**Comment by 7yl4r** [comment]
I also just noticed that bullets keep moving when paused as well. It's not critical, but it may be worth thinking about how we can incorporate pause state.

**Comment by BrianErikson** [comment]
Original issue resolved with commit 307045b16c7fbf73df9ba1675ee6c106c7302dee
