### ISSUE TITLE
basic text display

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#9]
Design and implement basic dialogue box. No plans yet on the design; that's open for discussion here.

Also be sure to search for existing solutions before custom-rolling one, since this is a pretty common game element.

**Comment by 7yl4r** [comment]
dialogue-box: ![image](https://cloud.githubusercontent.com/assets/1051390/8017844/6d8268e4-0bd0-11e5-98ed-0e5b1c8560b2.png)

or

text-bubble: ![image](https://cloud.githubusercontent.com/assets/1051390/8017848/97415906-0bd0-11e5-927c-fcba3de44cba.png)

I'm leaning towards the dialogue-box for simplicity, as I don't think the text-bubble offers much and may introduce a number of edge-cases based on speaker location.

**Comment by BrianErikson** [comment]
[Scene2D.UI.Dialog](http://libgdx.badlogicgames.com/nightlies/docs/api/com/badlogic/gdx/scenes/scene2d/ui/Dialog.html) has most of the legwork done for us. We might need to extend the class to make it have more flair, or so it prints like someone is talking. Of course, we will still need to deliver the story with an engine of some sort.
