### ISSUE TITLE
Split Another Monolith (EntityBuilder)

### ISSUE THREAD

**Issue by BrianErikson** [EmergentOrganization/cell-rpg#90]
Split `EntityBuilder` into builders for each separate type of entity:
- Scenery (no colliders, just static images)
- PhysicsObjects
- CAEntities

There might be a more intuitive way to split it, but something probably needs to be done to reduce the complexity yet again

**Comment by 7yl4r** [comment]
Could split by archetype?

**Comment by BrianErikson** [comment]
Split builders by component with commit dcb242cf4ee0d1a2b415d60b5b54af2948138a43
