### ISSUE TITLE
Code TODO List @ 13Jan2016

### ISSUE THREAD

**Issue by BrianErikson** [EmergentOrganization/cell-rpg#92]
TODO list is getting large -- maybe we should do something about that :+1: 
When TODOs are accomplished, please reply with changes or edit post and cross out each respective TODO. I couldn't find a good way to keep line numbers with grep so just use CTRL+F in each respective file to find the LOC
1. ~~CAGridComponents.java:  // location of grid center TODO: maybe a position component could be used for this?~~
2. CAGridComponents.java:  // TODO: use of inteface, enum, map like w/ CellRenderer is preferred.
3. ~~CAGridComponents.java:  // TODO: add pattern, row, col to queue which will be handled, call _stampState during next generation~~
4. ~~CAGridComponents.java:  // TODO: estimate should + a few ms; currently this is soonest possible time.~~
5. CAInteraction/CAInteractionList.java:  // TODO: (enhancement) could apply multiple stamps over multiple generations
6. CAInteraction/CAInteractionList.java:  // TODO: public void setColliderRadiusFromBounds(Bounds bounds){
7. CollectibleSpawnField.java:  // TODO: exclude inner radius / bounds?
8. CollectibleSpawnField.java:  // TODO: add rotation?
9. CollectibleSpawnField.java:  // TODO: incorporate variance
   - ~~9&3/4. Position.java:  // NOTE: this doesn't take into account rotation!  TODO: fix!~~
10. SpontaneousGeneration/SpontaneousGenerationList.java:  // TODO: exclude inner radius / bounds?
11. SpontaneousGeneration/SpontaneousGenerationList.java:  // TODO: incorporate variance
12. ~~StatsTracker.java: \* TODO: connect this with game events using EventManager.~~ 
    - Already done!
13. ~~BaseComponentBuilder.java:  // TODO: List required components somehow~~
    - Already done in a different class
14. ~~HealthBuilder.java:  // still destructible TODO: fix?~~
15. CALayerFactory.java: \* !!! DISCLAIMER: despite the name, this does not follow the factory pattern. !!! TODO: rename
16. CALayerFactory.java: \* TODO: this should be part of the CALayerComponentsConstructor, not a separate class.
17. ~~EntityFactory.java:  // TODO: add CAManager & get CA layers using , not this:~~
18. EntityFactory.java:  // TODO: not sure what this value should be... could use Bounds?
19. EntityFactory.java:  // TODO: not sure what this should be either
20. EntityFactory.java:  // TODO: Tie GridSeed component to this somehow
21. EntityFactory.java:  // TODO: Come up with a more ui-friendly name
22. EntityFactory.java:  // TODO: Come up with a more ui-friendly name
23. ~~EntityFactory.java:  // TODO: move this... somewhere...~~
24. CAStamps.java:  // TODO: randomize first col
25. PhysicsContactListener.java:  // TODO: add collide-events to CollideEffect?
26. ScoreEventListener.java:  // TODO: iff event applies to this entity
27. ~~PlayerInputProcessor.java:  // TODO: should be list of iMovementCtrl~~
28. ~~PlayerInputProcessor.java:  // TODO: add more movement control options~~
29. ~~PlayerInputProcessor.java:  // TODO: add more weapon control options~~
30. Arcade.java:  // TODO: this should be somewhere else
31. ~~DialogDisplay.java:  // align topLeft TODO: this isn't working...~~
32. LifeGeneLab.java:  // TODO: this should be somewhere else
33. SettingsMenu.java:  // TODO: audio settings
34. ~~ArcadeRegion.java:  // TODO: this is currently unused, but layers should be dynamically added/removed~~
35. ~~ArcadeRegion.java:  // TODO:    by a CA Manager.~~
36. ~~ArcadeRegion1.java:  // TODO: this is currently unused, but layers should be dynamically added/removed~~
37. ~~ArcadeRegion1.java:  // TODO:    by a CA Manager.~~
38. ~~ArcadeRegion2.java:  // TODO: this is currently unused, but layers should be dynamically added/removed~~
39. ~~ArcadeRegion2.java:  // TODO:    by a CA Manager.~~
40. ~~ArcadeRegion3.java:  // TODO: this is currently unused, but layers should be dynamically added/removed~~
41. ~~ArcadeRegion3.java:  // TODO:    by a CA Manager.~~
42. iRegion.java:    \* TODO: should this return the region class instead and leave instantiation to the regionSwitcher?
43. TheEdge.java:  // TODO: return adjoining region when nearing boundary
44. Story.java:  // TODO: this should be somewhere else
45. Story.java:  // TODO: change this region
46. CameraSystem.java:  // TODO: randomize directions
47. ~~CameraSystem.java:  // TODO: Need to replace this with 7yl4rs version~~
48. CAGenerationSystem.java:  // TODO: manage generation tasks somehow?
49. CAInteractionSystem.java:  // TODO: check cells past through since last collision check
50. CAInteractionSystemTest.java:  // TODO: re-write test to work around this, or at least expect error here.
51. CARenderSystem.java:  // TODO: handle key not found exception. print "Renderer for renderType not found", 
    default to ColorMap?
52. CA.java:  //    TODO: use this instead of getCAMap(). also do the same in CellRenderer.
53. BaseCell.java:  // TODO: true locks the cell, means "don't compute rule on this cell"
54. CellWithHistory.java:  // TODO: replace this with bufferSwapCell which should store two state values here,
55. GeneticCell.java:  // TODO: inherit + mutation
56. GeneticCell.java:  // TODO: add back version : v" + CellRpg.fetch().getVersion(),
57. util.java:  // TODO: check gridComps.CARule and execute appropriate rule
58. DGRN.java:  // TODO: this should should really be handled within the gexf4j library.
59. DGRN.java:  // TODO: this should should really be handled within the gexf4j library.
60. DGRN.java:  // TODO: this should should really be handled within the gexf4j library.
61. DGRN.java:  // TODO: this should != 0
62. DGRN.java:  // TODO: or maybe otherNode is not yet in grid!
63. DGRN.java:  // TODO: this should should really be handled within the gexf4j library.
64. DGRNTest.java:  // TODO: this doesn't work:
65. DGRNTest.java:  // TODO: this does work:
66. DGRNTest.java:  // TODO: WHY?
67. DGRNTest.java:  // TODO: compare node.getAllEdges() and node.getEdges()
68. DGRNTest.java:  // TODO: do either of the above include inflowing edges AND outflowing edges?
69. gexfTest.java:  // TODO: this test fails, attributes must be manually added to nodes.
70. gexfTest.java:  // TODO: this test fails. getAllEdges() always returns 0 edges
71. gexfTest.java:  // TODO: compare node.getAllEdges() and node.getEdges()
72. gexfTest.java:  // TODO: do either of the above include inflowing edges AND outflowing edges?
73. TimedDestructionSystem.java:  // TODO: use DelayedIteratingSystem instead
74. WindowSystem.java:  // TODO: frameBuffer not rendering for some reason
75. CGoLShapeConsts.java:  //TODO: return something like this instead:
76. MapEditor.java:  // TODO:move this with other scenes, and probably extend the WorldScene to reduce code duplication.
77. MapEditor.java:  //TODO
78. EditorWindow.java:  // TODO: Throw warning window saying that changes won't be saved if they continue
79. EditorWindow.java:  // TODO: rebuild colliders on resize
80. Resources.java:  // TODO sound effect
81. testUtils.java:  // TODO: format print. maybe .replace("],[", "\n") ?

**Comment by 7yl4r** [comment]
Heh. I am most definitely the culprit here. I have a bad(?) habit of leaving loose-suggestion TODOs all over the place.

**Comment by BrianErikson** [comment]
A lot of these are stale, and this issue has outlived it's usefulness

**Comment by 7yl4r** [comment]
up-to-date todo listing can now be viewed via [the codeclimate issues list](https://codeclimate.com/github/EmergentOrganization/cell-rpg/issues)
