### ISSUE TITLE
Equipment Gameplay Discussion

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#97]
We need some UI mockups for configuring/designing a weapons/equipment loadout. Imagine that the "planiverse bridge orb" has slots which can be configured or filled in different ways. Something like an [RPG inventory/equipment screen](http://consortium-game.com/images/ss5.jpg). 

This does raise the question of what exactly we are configuring. Here are some ideas:
1. energy allocation : the orb produces a set amount of energy which can be allocated to shields/weapons/propulsion.
2. weapon config : lots of small bullets, powerful accurate ones, or big explosions? 
3. drones / satellites : Eventually I would like this game to be more strategy/RPG than arcade shooter. The end-goal is to have orbiting satellite units operating semi-autonomously. Configuration of drones might include:
   1. selection of drones (which ones are you using)
   2. drone orbit (distance, speed, orbital shape)
   3. drone role / AI behavior (does the drone act as a shield trying to catch incoming shots or is it a fragile weapon which avoids incoming danger?)
   4. drone equipment configuration : energy allocation / weapon config for each drone

The introduction of satellites is a big change in gameplay as it exists now, but I think it is a neat idea we should pursue in the future. I'll post some mockups (eventually) and invite any and all discussion/thoughts/ideas on the concept.

**Comment by 7yl4r** [comment]
For energy balance I'm imagining a basic "energy unit allocation" screen:

![image](https://cloud.githubusercontent.com/assets/1051390/15452517/6d41d5be-1fbf-11e6-9368-3ead8d68e7a6.png)

**Comment by 7yl4r** [comment]
Equipment loadout using equipment "cards". The idea being that you collect equipment throughout the game and develop a particular set of equipment that you like.

![image](https://cloud.githubusercontent.com/assets/1051390/15452595/0a44f398-1fc3-11e6-9835-7379041a9e9f.png)

**Comment by 7yl4r** [comment]
The above energy balance concepts can apply to the player's Planiverse Bridge Orb, but could also be used later for satellite drones
![image](https://cloud.githubusercontent.com/assets/1051390/15452626/6906f84e-1fc4-11e6-8cb4-7b462871ca4c.png)

This would allow for multiple styles of play. Players could use equipment directly, or equip their satellites. Players could even equip satellites with satellites. This does sound like a bit of a balancing nightmare though.

**Comment by 7yl4r** [comment]
Or, hey... why not combine the two?
![image](https://cloud.githubusercontent.com/assets/1051390/15455699/4fb0bad6-202a-11e6-8012-c9d7ee3a486b.png)

This concept includes:
1. minimum operating energy for each module (blue/red) + energy allocated for use by module (green/black)
2. shield / weapon power / movement / submodules stats per module (rgb+cyan boxes)
3. module types via card coloration
4. energy requirements met & module damaged indicators (g/r on left)

Additional options in the "click to edit" screen (if applicable):   
1. module description
2. remove module from slot option
3. access edit submodules screen
4. access edit module config/mode screen

**Comment by 7yl4r** [comment]
The play styles I'm imagining are:
1. bezerker: lots of shields and maneuverability. Destroy things by bumping into them.
2. bullet-hell: Blow stuf up with guns. Lots of guns.
3. carrier: let your satellites do the work.

Ideally each would have weaknesses and strengths and the game story would encourage switching it up. Thinking about the balancing act here is making me very nervous though.

**Comment by 7yl4r** [comment]
[This drag-and-drop inventory implementation](http://pixelscientists.com/wordpress/?p=15) may be very helpful if we chose to pursue drag-and-drop or popup detail menus.

**Comment by BrianErikson** [comment]
Trello ported
