### ISSUE TITLE
EquipmentMenu alignment

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#98]
I can't figure out how to get the alignment of things to work in the `EquipmentMenu`. Ideally we want things to look as close to the UI mockups (see #97), but at a bare minimum we need the +/- buttons to align to the bottom so they are on either side of the energy display bar. This shouldn't be a hard thing to accomplish, but my attempts have been fruitless. Should be an easy fix for someone with more libgdx experience.

**Comment by BrianErikson** [comment]
![equipment menu](https://cloud.githubusercontent.com/assets/7645647/15801707/f2045270-2a9d-11e6-99d8-1a66e6e369ec.png)

Once we get more art in accordance with #97 I will finish this up

**Comment by 7yl4r** [comment]
I am soooo happy you figured this out. I couldn't believe how much trouble
I was having with this. Looks much better already.

**Comment by BrianErikson** [comment]
Yeah those Vertical/Horizontal groups seem to be pretty shoddy, so I switched them out for Tables. Not your fault at all, just a bad class
