### ISSUE TITLE
emergent2dCore do over

### ISSUE THREAD

**Issue by 7yl4r** [EmergentOrganization/cell-rpg#99]
I made the mistake of pushing too many classes into emergent2dCore before they were truly decoupled from cellRPG. The first step to fixing this mess is to move (nearly) everything back into this project. Then we can begin the slow process of moving things into the emergent2dCore.

**Comment by BrianErikson** [comment]
Re-integrated.. @7yl4r, feel free to close it out if the re-implementation looks good to you, and builds okay.

**Comment by 7yl4r** [comment]
:+1:
